# Generated by Django 6.0.8 on 2026-08-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='download_speed_mbps',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Download speed in Mbps, e.g. 5.00. Pushed to MikroTik as the profile's rate-limit.", max_digits=6),
        ),
        migrations.AddField(
            model_name='plan',
            name='upload_speed_mbps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upload speed in Mbps. Leave blank to use the same value as download.', max_digits=6, null=True),
        ),
    ]
