# Generated by Django 6.0.8 on 2026-09-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_download_speed_mbps_plan_upload_speed_mbps'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Hashed portal login password (set via set_password()) — NOT the MikroTik password', max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', help_text='Used to log in to the customer portal', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
