"""
Django settings for ispbilling project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!,
SECRET_KEY = 'django-insecure-+xefv2x1pf374u8@+4+9(=po1a5dl5_^re7ucw+!hu!c)bcy%^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["isp.haruvoster.co.ke", "www.isp.haruvoster.co.ke", '127.0.0.1', 'localhost']

CSRF_TRUSTED_ORIGINS = ["https://isp.haruvoster.co.ke", "https://www.isp.haruvoster.co.ke"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_celery_beat',
    'billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ispbilling.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ispbilling.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# M-Pesa Daraja settings — this is now the active payment provider (views.py
# calls mpesa.stk_push directly). Get these from https://developer.safaricom.co.ke
# after your Paybill/Till is approved: Consumer Key + Secret come from your
# Daraja app, Passkey from the "Lipa Na M-Pesa Online" product on your app,
# Shortcode is your actual Paybill/Till number. MPESA_CALLBACK_URL must be a
# real public HTTPS URL Safaricom can reach — replace yourdomain.com.
# REPLACE ALL FIVE VALUES BELOW before going live; sandbox works for testing
# with Safaricom's shared test shortcode/passkey in the meantime.
# Never commit real values to source control.
# ---------------------------------------------------------------------------
MPESA_ENV = "sandbox"  # change to "production" once you have real Daraja credentials
MPESA_CONSUMER_KEY = "DRemH02AWuvTBQvHfSY4rkwjGPzATYizI3J2H2mQFRwvy4TR"
MPESA_CONSUMER_SECRET = "zhAZ4G1GWRcNgq9Me735b3iGNKrPtDybNVX3y9A1TeApBYU25Ih117zjamoIiJTF"
MPESA_SHORTCODE = "174379"
MPESA_PASSKEY = "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
MPESA_CALLBACK_URL = "https://isp.haruvoster.co.ke/billing/mpesa/callback/"


# ---------------------------------------------------------------------------
# IntaSend — no longer used to initiate payments (views.py now calls Daraja
# directly via mpesa.stk_push). Left here only because intasend_webhook is
# still a valid endpoint if you ever accept payments through IntaSend again;
# it's safe to ignore these values otherwise.
# ---------------------------------------------------------------------------
INTASEND_PUBLISHABLE_KEY = "ISPubKey_live_bb1325db-379d-4189-ac2e-97a397f95ddf"
INTASEND_SECRET_KEY = "ISSecretKey_live_b1c15db4-0ca0-4b53-b514-9a1d56c7e4c9"
INTASEND_TEST_MODE = False  # switch to False once your IntaSend account is live
INTASEND_WEBHOOK_URL = "https://yourdomain.com/billing/intasend/webhook/"


# ---------------------------------------------------------------------------
# Africa's Talking — used to send OTP codes for phone verification on signup.
# Sign up at https://africastalking.com to get sandbox/production credentials.
# ---------------------------------------------------------------------------
AFRICASTALKING_USERNAME = "REPLACE_ME"
AFRICASTALKING_API_KEY = "REPLACE_ME"
AFRICASTALKING_SENDER_ID = ""  # optional; blank uses the shared shortcode


# ---------------------------------------------------------------------------
# Email — used to send the automatic monthly revenue-share invoice.
# Configure real SMTP credentials for production.
# ---------------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # swap for smtp in production
DEFAULT_FROM_EMAIL = "billing@yourdomain.com"


# ---------------------------------------------------------------------------
# Celery — background jobs for expiry checks and the monthly revenue invoice.
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TIMEZONE = TIME_ZONE
